name: Java CI with Coverage Enforcement

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests with coverage
        run: ./gradlew clean test jacocoTestReport jacocoTestCoverageVerification

      - name: Upload JaCoCo report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Dummy Deployment
        run: echo "Deploying application..."

